# Form implementation generated from reading ui file 'wlogin.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fromLogin(object):
    def setupUi(self, fromLogin):
        fromLogin.setObjectName("fromLogin")
        fromLogin.resize(661, 329)
        fromLogin.setMinimumSize(QtCore.QSize(661, 329))
        fromLogin.setMaximumSize(QtCore.QSize(661, 329))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Wehaa/wehaaportal.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        fromLogin.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=fromLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFondo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFondo.setGeometry(QtCore.QRect(0, 0, 331, 331))
        self.lblFondo.setText("")
        self.lblFondo.setPixmap(QtGui.QPixmap(":/App/loginbackgroup.png"))
        self.lblFondo.setScaledContents(True)
        self.lblFondo.setObjectName("lblFondo")
        self.txtUser = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtUser.setGeometry(QtCore.QRect(370, 150, 251, 31))
        self.txtUser.setStyleSheet("border: none;\n"
"border-left: 5px solid;\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(7, 126, 246, 205));\n"
"padding-left: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.txtUser.setClearButtonEnabled(True)
        self.txtUser.setObjectName("txtUser")
        self.txtPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtPass.setGeometry(QtCore.QRect(370, 200, 251, 31))
        self.txtPass.setStyleSheet("border: none;\n"
"border-left: 5px solid;\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(7, 126, 246, 205));\n"
"padding-left: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPass.setClearButtonEnabled(True)
        self.txtPass.setObjectName("txtPass")
        self.btnLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(430, 260, 131, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/png/icons8-enter-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnLogin.setIcon(icon1)
        self.btnLogin.setFlat(False)
        self.btnLogin.setObjectName("btnLogin")
        self.lblSlogan = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblSlogan.setGeometry(QtCore.QRect(110, 120, 131, 31))
        self.lblSlogan.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lblSlogan.setObjectName("lblSlogan")
        self.lblWelcome = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblWelcome.setGeometry(QtCore.QRect(80, 150, 181, 41))
        self.lblWelcome.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.lblWelcome.setObjectName("lblWelcome")
        self.lblLogo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLogo.setGeometry(QtCore.QRect(430, 60, 131, 61))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/App/fastfood.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setObjectName("lblLogo")
        self.logoWehaa = QtWidgets.QLabel(parent=self.centralwidget)
        self.logoWehaa.setGeometry(QtCore.QRect(10, 10, 31, 21))
        self.logoWehaa.setText("")
        self.logoWehaa.setPixmap(QtGui.QPixmap(":/Wehaa/wehaaportal.png"))
        self.logoWehaa.setScaledContents(True)
        self.logoWehaa.setObjectName("logoWehaa")
        fromLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(fromLogin)
        QtCore.QMetaObject.connectSlotsByName(fromLogin)

    def retranslateUi(self, fromLogin):
        _translate = QtCore.QCoreApplication.translate
        fromLogin.setWindowTitle(_translate("fromLogin", "Iniciar Sesión"))
        self.txtUser.setPlaceholderText(_translate("fromLogin", "Usuario ID"))
        self.txtPass.setPlaceholderText(_translate("fromLogin", "Contraseña"))
        self.btnLogin.setText(_translate("fromLogin", "Iniciar"))
        self.lblSlogan.setText(_translate("fromLogin", "Nice to see you again"))
        self.lblWelcome.setText(_translate("fromLogin", "Welcome Back"))
        self.logoWehaa.setToolTip(_translate("fromLogin", "Wehaa Portal Soft."))

'''
import resource

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fromLogin = QtWidgets.QMainWindow()
    ui = Ui_fromLogin()
    ui.setupUi(fromLogin)
    fromLogin.show()
    sys.exit(app.exec())
'''